export const BRAND = {
  name: "Cebu's Ayers Lechon",
  logo: "/logo.png",
  heroImage: "/hero-img.jpg",
  heroProducts: {
    lechonBelly: "/hero-lechon-belly.jpg",
    wholeLechon: "/hero-lechon-whole.jpg",
    friedChicken: "/hero-fried-chicken.jpg",
  },
  menuPricelist: "/menu-pricelist.png",
  tagline: "Authentic Cebu Lechon, Roasted to Perfection",
  phone: "(032) 268-0327",
  phoneAlt: "(032) 231-7615",
  mobile: "0927-440-6891",
  mobileAlt: "0922-826-8133",
  email: "hello@ayerlechon.com",
  facebook: "https://www.facebook.com/",
  facebookLabel: "Follow us on Facebook",
  deliveryNote: "Free door-to-door delivery within Metro Cebu & Metro Manila.",
  priceDisclaimer: "Prices are subject to change without prior notice.",
} as const;

export const MENU_CATEGORIES = [
  { id: "KINUTSON", label: "Kinutchillo (Half Lechon)" },
  { id: "BONELESS_BELLY", label: "Boneless Belly Lechon" },
  { id: "LECHON_REGULAR", label: "Lechon Regular (Whole)" },
] as const;

export const ORDER_TYPES = [
  { id: "DINE_IN", label: "Dine-in" },
  { id: "TAKEOUT", label: "Takeout" },
  { id: "DELIVERY", label: "Delivery" },
  { id: "EVENT_CATERING", label: "Event / Catering" },
] as const;

export const AUTH_COOKIE = "ayer_admin_token";

/** Official menu from Ayers Lechon price list */
export const BASE_MENU_ITEMS = [
  {
    name: "Kinutchillo SWAK",
    description: "Half lechon perfect for smaller gatherings. Classic Cebu-style crispy skin and tender meat.",
    price: 5500,
    category: "KINUTSON",
    sizes: "Half · 10–14 persons · Freight ₱700",
    imageUrl: "/hero-lechon.png",
    sortOrder: 1,
  },
  {
    name: "Kinutchillo SAKTO",
    description: "Just-right half lechon for medium-sized family celebrations and office events.",
    price: 5750,
    category: "KINUTSON",
    sizes: "Half · 15–17 persons · Freight ₱700",
    imageUrl: "/hero-lechon.png",
    sortOrder: 2,
  },
  {
    name: "Kinutchillo SULIT",
    description: "Generous half lechon — best value for bigger groups without ordering a whole pig.",
    price: 6250,
    category: "KINUTSON",
    sizes: "Half · 18–20 persons · Freight ₱700",
    imageUrl: "/hero-lechon.png",
    sortOrder: 3,
  },
  {
    name: "Regular Belly Lechon",
    description: "Boneless belly lechon with golden crackling skin — a Cebu favorite for sharing.",
    price: 3610,
    category: "BONELESS_BELLY",
    sizes: "15–20 persons · Freight ₱700",
    imageUrl: "https://images.unsplash.com/photo-1606755962773-d324e166a853?w=800&q=80",
    sortOrder: 4,
  },
  {
    name: "Spicy Belly Lechon",
    description: "Boneless belly lechon with a bold spicy kick — same crispy perfection, extra heat.",
    price: 3810,
    category: "BONELESS_BELLY",
    sizes: "15–20 persons · Freight ₱700",
    imageUrl: "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=800&q=80",
    sortOrder: 5,
  },
  {
    name: "Lechon Regular — De Leche",
    description: "Whole lechon (de leche size) — the star of every Cebu fiesta and family reunion.",
    price: 9000,
    category: "LECHON_REGULAR",
    sizes: "11–12 kls · 20–30 persons · +₱150 for spicy",
    imageUrl: "/hero-lechon.png",
    sortOrder: 6,
  },
  {
    name: "Lechon Regular — Size A",
    description: "Whole lechon roasted to perfection for medium-large celebrations.",
    price: 9500,
    category: "LECHON_REGULAR",
    sizes: "13–15 kls · 31–35 persons · +₱150 for spicy",
    imageUrl: "/hero-lechon.png",
    sortOrder: 7,
  },
  {
    name: "Lechon Regular — Size B",
    description: "A crowd-favorite whole lechon for birthdays, baptisms, and office parties.",
    price: 10500,
    category: "LECHON_REGULAR",
    sizes: "16–18 kls · 36–40 persons · +₱150 for spicy",
    imageUrl: "/hero-lechon.png",
    sortOrder: 8,
  },
  {
    name: "Lechon Regular — Size C",
    description: "Generous whole lechon for large gatherings and community feasts.",
    price: 11500,
    category: "LECHON_REGULAR",
    sizes: "19–21 kls · 41–50 persons · +₱150 for spicy",
    imageUrl: "/hero-lechon.png",
    sortOrder: 9,
  },
  {
    name: "Lechon Regular — Size D",
    description: "Premium whole lechon for grand celebrations and corporate events.",
    price: 12140,
    category: "LECHON_REGULAR",
    sizes: "22–24 kls · 51–60 persons · +₱150 for spicy",
    imageUrl: "/hero-lechon.png",
    sortOrder: 10,
  },
  {
    name: "Lechon Regular — Size E",
    description: "Extra-large whole lechon for major fiestas and milestone celebrations.",
    price: 12364,
    category: "LECHON_REGULAR",
    sizes: "25–27 kls · 61–65 persons · +₱150 for spicy",
    imageUrl: "/hero-lechon.png",
    sortOrder: 11,
  },
  {
    name: "Lechon Regular — Size F",
    description: "One of our largest whole lechon sizes — built for big Cebu celebrations.",
    price: 12700,
    category: "LECHON_REGULAR",
    sizes: "28–30 kls · 66–75 persons · +₱150 for spicy",
    imageUrl: "/hero-lechon.png",
    sortOrder: 12,
  },
  {
    name: "Lechon Regular — Size G",
    description: "Our biggest whole lechon — the ultimate centerpiece for grand occasions.",
    price: 14000,
    category: "LECHON_REGULAR",
    sizes: "31–35 kls · 76–90 persons · +₱150 for spicy",
    imageUrl: "/hero-lechon.png",
    sortOrder: 13,
  },
] as const;
